# Generated by Django 3.0.3 on 2020-02-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0003_ttbprevstep_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtbDjSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='chat id')),
                ('chat_name', models.TextField(verbose_name='chat name')),
                ('participants_count', models.BigIntegerField(default=0, verbose_name='participants_count')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
        migrations.AddField(
            model_name='ttbuser',
            name='subscriber',
            field=models.ManyToManyField(to='djh_app.TtbDjSubscriber', verbose_name='subscriber'),
        ),
        migrations.CreateModel(
            name='TtbDjChatAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('chat', models.TextField(verbose_name='chat')),
                ('permissions', models.TextField(verbose_name='user update')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djh_app.TtbDjSubscriber', verbose_name='subscriber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djh_app.TtbUser', verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'subscriber')},
            },
        ),
    ]
