# Generated by Django 3.0.6 on 2020-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0004_ttb_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttbuser',
            name='is_bot',
            field=models.NullBooleanField(default=None, verbose_name='is bot'),
        ),
    ]
