# Generated by Django 3.0.6 on 2020-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0005_ttbuser_is_bot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputMessage',
        ),
    ]
