# Generated by Django 3.0.6 on 2020-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0006_delete_inputmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtbDjLimitedButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=64, unique=True, verbose_name='index')),
                ('buttons', models.TextField(verbose_name='user update')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated')),
            ],
        ),
    ]
