# Generated by Django 3.0.7 on 2020-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0009_auto_20200617_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttbdjchatavailable',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
    ]
