# Generated by Django 3.0.7 on 2020-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0010_auto_20200619_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttbdjsubscriber',
            name='chat_type',
            field=models.CharField(default='chat', max_length=10, verbose_name='chat_type'),
        ),
    ]
