# Generated by Django 3.0.7 on 2020-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0012_ttbdjsubscriber_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttbuser',
            name='is_bot',
            field=models.BooleanField(default=None, null=True, verbose_name='is bot'),
        ),
    ]
