# Generated by Django 3.1.4 on 2020-12-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djh_app', '0013_auto_20201112_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttbdjsubscriber',
            options={'ordering': ('chat_type', 'chat_name')},
        ),
        migrations.AlterModelOptions(
            name='ttbuser',
            options={'ordering': ('name', 'username')},
        ),
    ]
